apiVersion: apps/v1
kind: Deployment
metadata:
  name: epam24-task01-deployment
  labels:
    app : my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      project: pod-nginx
  template:
    metadata:
      labels:
        project: pod-nginx
    spec:
      containers:
        - name: nginx-server
          image: nginx:latest
          ports:
            - containerPort: 80
