apiVersion: v1
kind: PersistentVolume
metadata:
  name: task03-nfs-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/nfs_share"
    server: 192.168.1.191
