apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy_view_clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: [list]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: [list]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy_view_clusterrole_binding
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_view_clusterrole
  apiGroup: rbac.authorization.k8s.io
